### ISSUE TITLE
ModuleNotFoundError: No module named '"tc_redis'

### ISSUE THREAD

**Issue by shudack** [thumbor-community/redis#14]
Hi,

I installed tc_redis in my dockerfile:
RUN pip3 install --no-cache-dir -r requirements.txt
...

requirements.txt:
tc_redis
...

thumbor.conf:
STORAGE = "tc_redis.storages.redis_storage"
REDIS_STORAGE_IGNORE_ERRORS = True
REDIS_STORAGE_SERVER_PORT = 6379
REDIS_STORAGE_SERVER_HOST = "localhost"
REDIS_STORAGE_SERVER_DB = 0
REDIS_STORAGE_SERVER_PASSWORD = None
REDIS_STORAGE_MODE = "single_node"
RESULT_STORAGE = "tc_redis.result_storages.redis_result_storage"
REDIS_RESULT_STORAGE_IGNORE_ERRORS = True
REDIS_RESULT_STORAGE_SERVER_PORT = 6379
REDIS_RESULT_STORAGE_SERVER_HOST = "localhost"
REDIS_RESULT_STORAGE_SERVER_DB = 0
REDIS_RESULT_STORAGE_SERVER_PASSWORD = None
REDIS_RESULT_STORAGE_MODE = "single_node"
...

And got this error when running thumbor container:
`Attaching to thumbor-thumbor-1
thumbor-thumbor-1  | ---> Starting thumbor with 4 processes...
thumbor-thumbor-1  | Traceback (most recent call last):
thumbor-thumbor-1  |   File "/home/thumbor/venv/bin/thumbor", line 8, in <module>
thumbor-thumbor-1  |     sys.exit(main())
thumbor-thumbor-1  |   File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/server.py", line 158, in main
thumbor-thumbor-1  |     importer = get_importer(config)
thumbor-thumbor-1  |   File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/server.py", line 63, in get_importer
thumbor-thumbor-1  |     importer.import_modules()
thumbor-thumbor-1  |   File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/importer.py", line 84, in import_modules
thumbor-thumbor-1  |     self.import_item("STORAGE", "Storage")
thumbor-thumbor-1  |   File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/importer.py", line 144, in import_item
thumbor-thumbor-1  |     module = self.import_class(f"{conf_value}.{class_name}")
thumbor-thumbor-1  |   File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/importer.py", line 56, in import_class
thumbor-thumbor-1  |     kls = import_class(name, get_module)
thumbor-thumbor-1  |   File "/home/thumbor/venv/lib/python3.9/site-packages/thumbor/importer.py", line 20, in import_class
thumbor-thumbor-1  |     module = import_module(module_name)
thumbor-thumbor-1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
thumbor-thumbor-1  |     return _bootstrap._gcd_import(name[level:], package, level)
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
thumbor-thumbor-1  |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
thumbor-thumbor-1  | ModuleNotFoundError: No module named '"tc_redis'
thumbor-thumbor-1 exited with code 1`

thumbor version: 7.4.7
python version: 3.9

I missed something?

**Comment by shudack** [comment]
Is working again. I will close the issue.
